<a href="https://colab.research.google.com/github/AadityaAdh/Back_Propagation/blob/main/back_prop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,InputLayer
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import mse
import numpy as np

In [ ]:
def build_model():
  model=Sequential()
  model.add(InputLayer(input_shape=(2,)))
  model.add(Dense(2,activation='sigmoid'))
  model.add(Dense(2,activation='sigmoid'))
  return model

In [ ]:
model=build_model()
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 2)                 6         
                                                                 
 dense_7 (Dense)             (None, 2)                 6         
                                                                 
Total params: 12 (48.00 Byte)
Trainable params: 12 (48.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
weights_and_biases = [
    np.array([[1.1261417, 0.22808969], [0.9494957, -0.86430585]]),
    np.array([0.0, 0.0]),
    np.array([[-0.64400184, -0.8975538], [0.08083081, 0.160573]]),
    np.array([0.0, 0.0])
]


model.set_weights(weights_and_biases)

In [ ]:
model.trainable_variables

[<tf.Variable 'dense_6/kernel:0' shape=(2, 2) dtype=float32, numpy=
 array([[ 1.1261417 ,  0.22808969],
        [ 0.9494957 , -0.86430585]], dtype=float32)>,
 <tf.Variable 'dense_6/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>,
 <tf.Variable 'dense_7/kernel:0' shape=(2, 2) dtype=float32, numpy=
 array([[-0.64400184, -0.8975538 ],
        [ 0.08083081,  0.160573  ]], dtype=float32)>,
 <tf.Variable 'dense_7/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>]

In [ ]:
x=np.array([0.05,0.10])
x=np.reshape(x,(1,2))
x

array([[0.05, 0.1 ]])

In [ ]:
model.predict(x)

1/1 [==============================] - 0s 52ms/step


array([[0.42374778, 0.40002128]], dtype=float32)

In [ ]:
optimizer = Adam(learning_rate=0.01)
model.compile(optimizer=optimizer, loss=mse)

In [ ]:
x = np.array([[0.05, 0.10]])
y = np.array([[0.01, 0.99]])

x.reshape(1,2)
y.reshape(1,2)

array([[0.01, 0.99]])

In [ ]:
model.fit(x, y, epochs=1, verbose=1)

1/1 [==============================] - 1s 522ms/step - loss: 0.2596


In [ ]:
model.trainable_variables

[<tf.Variable 'dense_4/kernel:0' shape=(2, 2) dtype=float32, numpy=
 array([[ 1.1161826 ,  0.23791872],
        [ 0.9395162 , -0.8543921 ]], dtype=float32)>,
 <tf.Variable 'dense_4/bias:0' shape=(2,) dtype=float32, numpy=array([-0.00999788,  0.00999125], dtype=float32)>,
 <tf.Variable 'dense_5/kernel:0' shape=(2, 2) dtype=float32, numpy=
 array([[-0.6540012 , -0.8875543 ],
        [ 0.07083153,  0.17057247]], dtype=float32)>,
 <tf.Variable 'dense_5/bias:0' shape=(2,) dtype=float32, numpy=array([-0.00999962,  0.00999971], dtype=float32)>]

In [ ]:
with tf.GradientTape() as tape:
    y_pred = model(x)
    loss = mse(y, y_pred)


grads = tape.gradient(loss, model.trainable_variables)

In [ ]:
grads

[<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 0.00077092, -0.00018187],
        [ 0.00154184, -0.00036374]], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.01541838, -0.00363745], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 0.05432877, -0.07614289],
        [ 0.04862152, -0.06814406]], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.10103125, -0.14159739], dtype=float32)>]

In [ ]:
a=[[1,2],[3,4],[5,6]]
b=["a","b","c"]
c=list(zip(a,b))
c

[([1, 2], 'a'), ([3, 4], 'b'), ([5, 6], 'c')]

In [ ]:
model.apply_gradients(zip(grads, model.trainable_variables))

AttributeError: 'Sequential' object has no attribute 'apply_gradients'